apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-service
spec:
  selector:
    matchLabels:
      app: rating-service
  replicas: 1
  template:
    metadata:
      labels:
        app: rating-service
    spec:
      containers:
        - name: rating-service  
          image: rating-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082  