apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
spec:
  selector:
    matchLabels:
      app: hotel-service
  replicas: 1
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
        - name: hotel-service 
          image: hotel-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081  
